apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quak
  labels:
    app.kubernetes.io/name: quak
    app.kubernetes.io/component: server
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: quak
      app.kubernetes.io/component: server
